### ISSUE TITLE
Table suddenly stop working/ rendering

### ISSUE THREAD

**Issue by KiddoV** [VisActor/VTable#1665]
I am not sure if this is a bug or not, but my table was working fine yesterday. Today, I came in and update to the newer version of the VTable to ``0.25.2``, then my table suddenly stop rendering and the console displayed this error:
```
@visactor_vtable.js:11669  Uncaught (in promise) TypeError: application.graphicService.creator[graphicType] is not a function
    at ScrollBar.createOrUpdateChild (@visactor_vtable.js:11669:116)
    at ScrollBar.render (@visactor_vtable.js:44578:171)
    at TableComponent.createScrollBar (@visactor_vtable.js:95506:25)
    at new TableComponent (@visactor_vtable.js:95320:10)
    at Scenegraph.createComponent (@visactor_vtable.js:99207:22)
    at new Scenegraph (@visactor_vtable.js:99107:114)
    at new BaseTable (@visactor_vtable.js:104215:1365)
    at new ListTable (@visactor_vtable.js:107506:197)
    at v-table.svelte:273:13
    at run (chunk-2SWUXKJS.js:19:10)
```
![err](https://github.com/VisActor/VTable/assets/28552977/6bda45c0-1ecb-4a36-89e4-0b5bd22c90a1)

I have tried downgraded to lower version ``0.25.0``, deleted the ``node_modules`` and ``package-lock.json`` entirely, and downloaded all again but it didn't help.

Now my app just came broken with the table. I have tried many thing, I don't know what to do now. Please help!

Thanks,

**Comment by Rui-Sun** [comment]
It is a peerDependencies version problem. You can use `npm install --legacy-peer-deps` temporarily, we will fix it ASAP.

**Comment by KiddoV** [comment]
I got this error, trying to run the app after ``npm install --legacy-peer-deps``:
```console
[vite]: Rollup failed to resolve import "@visactor/vrender-core" from "node_modules/@visactor/vutils-extension/es/utils/text.js".
    This is most likely unintended because it can break your application at runtime.
    If you do want to externalize this module explicitly add it to
    `build.rollupOptions.external`
    error during build:
    Error: [vite]: Rollup failed to resolve import "@visactor/vrender-core" from "node_modules/@visactor/vutils-extension/es/utils/text.js".       
    This is most likely unintended because it can break your application at runtime.
    If you do want to externalize this module explicitly add it to
    `build.rollupOptions.external`
        at onRollupWarning (file:///___/frontend/node_modules/vite/dist/node/chunks/dep-372dab03.js:45909:19) 
        at onwarn (file:///___/frontend/node_modules/vite/dist/node/chunks/dep-372dab03.js:45680:13)
        at Object.onwarn (file:///___/frontend/node_modules/rollup/dist/es/shared/rollup.js:23263:13)
        at ModuleLoader.handleResolveId (file:///___/frontend/node_modules/rollup/dist/es/shared/rollup.js:22158:26)
        at file:///___/frontend/node_modules/rollup/dist/es/shared/rollup.js:22119:26
```
I will just wait for the fix then. Thanks!

**Comment by KiddoV** [comment]
Any update on this one?

**Comment by Rui-Sun** [comment]
> Any update on this one?

you can try 0.25.5 version

**Comment by KiddoV** [comment]
> you can try 0.25.5 version

I already tried 0.25.5, still the same issue ☹
