### ISSUE TITLE
[Bug] 甘特图 taskBar move 和 resize存在bug

### ISSUE THREAD

**Issue by maInfinity** [VisActor/VTable#3221]
### Version

1.14.1

### Link to Minimal Reproduction

https://visactor.com/vtable/demo/gantt/gantt-basic

### Steps to Reproduce

1. 设置resizable : fasle时，移动鼠标到taskbar上
2. move 或 resize taskbar时，事件结束时 taskbar 有至少一端位于表格外侧（即看不见的地方）

### Current Behavior

![Vtablebug1](https://github.com/user-attachments/assets/a895502f-074d-4a3d-932e-80554df806c7)
![vtable bug2](https://github.com/user-attachments/assets/b68b1fbb-afa0-4d78-93e1-0abadfca3a2d)

### Expected Behavior

1. 第一种情况不应该报错
2. 第二种情况需要解决

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by fangsmile** [comment]
最新版应该解决了 试一下吧

**Comment by maInfinity** [comment]
感谢回复。
《设置resizable : fasle时，移动鼠标到taskbar上》 这个问题已经解决了。

但问题2，move taskbar时，如果taskbar 有部分被移动到表格外侧时（即看不见的地方），仍然会报错：
VM2546:17 Uncaught TypeError: Cannot read properties of undefined (reading 'startDate')
    at zH.endMoveTaskBar (eval at p (load-DF70S3rE.js:1:166), <anonymous>:17:941543)
    at HTMLDocument.a (eval at p (load-DF70S3rE.js:1:166), <anonymous>:17:932757)
    
   用官方的测试例子，设置版本为最新的1.14.3，仍然会出现上述错误。
   具体复现方式可以参考图片
![image](https://github.com/user-attachments/assets/a920da6c-5f19-47aa-be4c-23c980397b1c)

**Comment by fangsmile** [comment]
第2个问题 转换成feature解决掉了  这周会发版本。
当拖拽超出甘特图原本的日期范围后 会自动扩展日期范围，结合taskbar.moveToExtendDateRange 配置 默认开启

**Comment by maInfinity** [comment]
感谢回复。请问这周即将发的新版本中，当拖拽超出甘特图原本的日期范围后，如果不希望自动扩展日期范围，而是希望alert一个消息，并且让本次拖拽无效，moveToExtendDateRange这个配置能做到吗
